spring:
  application:
    name: projectMgr
  profiles:
    active: dev
#  mvc:
#    view:
#      suffix: .html
#      prefix: pages/
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080


upload-dir: ./upload/

